In [1]:
import numpy as np

# Input (4 samples, 2 features)
X = np.array([[0,0],[0,1],[1,0],[1,1]])

# Target (XOR)
Y = np.array([[0],[1],[1],[0]])

# Weights
W1 = np.random.randn(2,3)
W2 = np.random.randn(3,1)

# Activation
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Derivative
def dsigmoid(x):
    return x*(1-x)

lr = 0.1

for epoch in range(1000):

    # Forward
    H = sigmoid(X @ W1)
    O = sigmoid(H @ W2)

    # Error
    error = Y - O

    # Backward
    dO = error * dsigmoid(O)
    dH = (dO @ W2.T) * dsigmoid(H)

    # Update
    W2 += lr * H.T @ dO
    W1 += lr * X.T @ dH

print(O)

[[0.36977749]
 [0.51030659]
 [0.5636093 ]
 [0.55644531]]


In [3]:
import torch

torch.manual_seed(42)

# Xavier Initialization
def xavier(in_features, out_features):
    return torch.randn(in_features, out_features) * (2 / (in_features + out_features)) ** 0.5

# He Initialization
def he(in_features, out_features):
    return torch.randn(in_features, out_features) * (2 / in_features) ** 0.5

# Input
x = torch.randn(32, 64)

# Choose Initialization
W = he(64, 64)          # Change to xavier(64, 64) for Xavier initialization

# 20-layer MLP
for i in range(20):
    x = torch.relu(x @ W)

print("Final Output Shape:", x.shape)
print("Mean:", x.mean().item())
print("Variance:", x.var().item())

Final Output Shape: torch.Size([32, 64])
Mean: 18.059673309326172
Variance: 526.4692993164062


In [4]:
import numpy as np

# Input Image (5x5)
image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 2, 3],
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 0]
])

# 3x3 Filter
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Output Size
h, w = image.shape
k = kernel.shape[0]

output = np.zeros((h - k + 1, w - k + 1))

# Convolution
for i in range(h - k + 1):
    for j in range(w - k + 1):
        region = image[i:i+k, j:j+k]
        output[i, j] = np.sum(region * kernel)

print("Output:")
print(output)

Output:
[[-6. 12. 12.]
 [-6.  8.  8.]
 [-6.  2. 12.]]


In [5]:
import torch

torch.manual_seed(42)

# Parameter to optimize
w = torch.tensor([5.0])

# Gradient
grad = torch.tensor([2.0])

# Adam parameters
lr = 0.01
beta1 = 0.9
beta2 = 0.999
eps = 1e-8

m = torch.zeros_like(w)
v = torch.zeros_like(w)

for t in range(1, 11):

    # Update moments
    m = beta1 * m + (1 - beta1) * grad
    v = beta2 * v + (1 - beta2) * grad**2

    # Bias correction
    m_hat = m / (1 - beta1**t)
    v_hat = v / (1 - beta2**t)

    # Adam update
    w = w - lr * m_hat / (torch.sqrt(v_hat) + eps)

    print(f"Step {t}: {w.item():.4f}")

Step 1: 4.9900
Step 2: 4.9800
Step 3: 4.9700
Step 4: 4.9600
Step 5: 4.9500
Step 6: 4.9400
Step 7: 4.9300
Step 8: 4.9200
Step 9: 4.9100
Step 10: 4.9000


In [6]:
import torch

torch.manual_seed(42)

# Input (4 samples, 3 features)
x = torch.randn(4, 3)

# Learnable parameters
gamma = torch.ones(3)
beta = torch.zeros(3)

# Mean and Variance
mean = x.mean(dim=0)
var = x.var(dim=0, unbiased=False)

# Normalize
x_hat = (x - mean) / torch.sqrt(var + 1e-5)

# Batch Normalization
y = gamma * x_hat + beta

print("Input:\n", x)
print("\nNormalized Output:\n", y)

Input:
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])

Normalized Output:
 tensor([[-0.5067,  0.6239, -0.2637],
        [-0.6339, -1.3134, -1.4275],
        [ 1.7302, -0.5630,  0.3647],
        [-0.5896,  1.2525,  1.3264]])


In [7]:
import torch

torch.manual_seed(42)

# Input sequence (5 time steps, 3 features)
x = torch.randn(5, 3)

# Hidden size
hidden_size = 4

# Forward hidden state
h_f = torch.zeros(hidden_size)

# Backward hidden state
h_b = torch.zeros(hidden_size)

# Weights
W = torch.randn(3, hidden_size)

# Forward pass
forward_output = []
for t in range(len(x)):
    h_f = torch.tanh(x[t] @ W + h_f)
    forward_output.append(h_f)

# Backward pass
backward_output = []
for t in reversed(range(len(x))):
    h_b = torch.tanh(x[t] @ W + h_b)
    backward_output.insert(0, h_b)

# Combine forward and backward outputs
bilstm_output = torch.cat(
    (torch.stack(forward_output),
     torch.stack(backward_output)),
    dim=1
)

print(bilstm_output)

tensor([[ 0.3904,  0.5950,  0.3598, -0.1757,  0.8786,  0.3933,  0.6094, -0.7013],
        [ 0.8632, -0.5861, -0.2289, -0.0813,  0.9575, -0.2697,  0.3312, -0.6923],
        [ 0.9990,  0.9217,  0.8222, -0.8673,  0.9991,  0.9901,  0.9371, -0.9466],
        [ 0.9046,  0.9770,  0.8963, -0.6774,  0.8877,  0.4666,  0.3207, -0.5570],
        [ 0.9852, -0.1184,  0.5287, -0.9035,  0.9131, -0.7991, -0.2986, -0.6715]])


In [8]:
import torch
import torch.nn as nn

class ResidualBlock(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(3, 3, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.conv2 = nn.Conv2d(3, 3, kernel_size=3, padding=1)

    def forward(self, x):
        identity = x
        out = self.conv1(x)
        out = self.relu(out)
        out = self.conv2(out)
        out = out + identity      # Skip Connection
        out = self.relu(out)
        return out

# Input
x = torch.randn(1, 3, 32, 32)

# Model
model = ResidualBlock()

# Output
y = model(x)

print("Output Shape:", y.shape)

Output Shape: torch.Size([1, 3, 32, 32])


In [9]:
import torch
import torch.nn as nn

class SimpleUNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.encoder = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.decoder = nn.Conv2d(16, 1, kernel_size=3, padding=1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.encoder(x))
        x = self.sigmoid(self.decoder(x))
        return x

# Input Image
x = torch.randn(1, 3, 128, 128)

# Model
model = SimpleUNet()

# Output Mask
output = model(x)

print("Segmentation Mask Shape:", output.shape)

Segmentation Mask Shape: torch.Size([1, 1, 128, 128])


In [10]:
import torch
import torch.nn.functional as F

# Predicted box (x1, y1, x2, y2)
pred_box = torch.tensor([10., 10., 30., 30.])

# Ground truth box
true_box = torch.tensor([15., 15., 35., 35.])

# IoU Function
def iou(box1, box2):
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    inter = max(0, x2-x1) * max(0, y2-y1)
    area1 = (box1[2]-box1[0]) * (box1[3]-box1[1])
    area2 = (box2[2]-box2[0]) * (box2[3]-box2[1])

    return inter / (area1 + area2 - inter)

# CIoU Loss (Simplified)
ciou_loss = 1 - iou(pred_box, true_box)

# Classification Loss
pred_class = torch.tensor([[2.0, 0.5]])
true_class = torch.tensor([0])

cls_loss = F.cross_entropy(pred_class, true_class)

print("CIoU Loss:", ciou_loss.item())
print("Classification Loss:", cls_loss.item())

CIoU Loss: 0.6086956262588501
Classification Loss: 0.2014133334159851


In [11]:
import torch
import torch.nn as nn

# Generator
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(100, 28 * 28)

    def forward(self, z):
        return self.fc(z)

# Critic
class Critic(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(28 * 28, 1)

    def forward(self, x):
        return self.fc(x)

G = Generator()
C = Critic()

# Random Noise
z = torch.randn(4, 100)

# Fake Image
fake = G(z)

# Critic Score
score = C(fake)

# Wasserstein Loss
loss = -score.mean()

print("WGAN Loss:", loss.item())

WGAN Loss: -0.3297749161720276


In [12]:
import torch
import torch.nn as nn

# Input Image (1 image, 3 channels, 32x32)
x = torch.randn(1, 3, 32, 32)

# Patch Embedding
patch_embed = nn.Conv2d(3, 64, kernel_size=4, stride=4)

# Convert image into patches
patches = patch_embed(x)

# Flatten patches
patches = patches.flatten(2).transpose(1, 2)

# Multi-Head Self Attention
attention = nn.MultiheadAttention(embed_dim=64, num_heads=4, batch_first=True)

output, _ = attention(patches, patches, patches)

print("Output Shape:", output.shape)

Output Shape: torch.Size([1, 64, 64])


In [13]:
import torch
import torch.nn as nn

# Convolutional Autoencoder
class AutoEncoder(nn.Module):
    def __init__(self):
        super().__init__()

        # Encoder
        self.encoder = nn.Sequential(
            nn.Conv2d(1, 8, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        # Decoder
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(8, 1, 2, stride=2),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x

# Input Image
x = torch.randn(1, 1, 28, 28)

# Model
model = AutoEncoder()

# Reconstructed Image
output = model(x)

print("Output Shape:", output.shape)

Output Shape: torch.Size([1, 1, 28, 28])


In [14]:
import torch
import torch.nn as nn

# Simple TCN
class TCN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(1, 8, kernel_size=3, padding=2, dilation=1)
        self.conv2 = nn.Conv1d(8, 16, kernel_size=3, padding=4, dilation=2)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.relu(self.conv2(x))
        return x

# Input (Batch, Channels, Sequence Length)
x = torch.randn(1, 1, 20)

# Model
model = TCN()

# Output
output = model(x)

print("Output Shape:", output.shape)

Output Shape: torch.Size([1, 16, 26])


In [15]:
import torch
import torch.nn as nn

# Custom Swish Activation
class Swish(nn.Module):
    def forward(self, x):
        return x * torch.sigmoid(x)

# Input
x = torch.randn(2, 5)

# Swish Layer
swish = Swish()

# Output
output = swish(x)

print("Input:")
print(x)

print("\nOutput:")
print(output)

Input:
tensor([[-0.2384, -0.4263, -0.9570, -0.4171,  1.3134],
        [ 1.0289, -0.5759, -0.1554, -2.6169, -0.3309]])

Output:
tensor([[-0.1050, -0.1684, -0.2655, -0.1657,  1.0350],
        [ 0.7580, -0.2072, -0.0717, -0.1781, -0.1383]])


In [19]:
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

def main():
    # Set environment variables for single-process distributed training simulation.
    # These are typically set by a distributed launcher (e.g., torch.run).
    # For a single process in Colab, we simulate rank 0 out of 1 total process.
    os.environ['MASTER_ADDR'] = 'localhost'  # Required for GLOO backend
    os.environ['MASTER_PORT'] = '29500'      # Required for GLOO backend, pick an unused port
    os.environ['RANK'] = '0'                 # This process is rank 0
    os.environ['WORLD_SIZE'] = '1'           # Total number of processes is 1
    os.environ['LOCAL_RANK'] = '0'           # Local rank for this process is 0

    # Initialize the process group
    dist.init_process_group(backend="gloo", rank=int(os.environ['RANK']), world_size=int(os.environ['WORLD_SIZE']))

    local_rank = int(os.environ["LOCAL_RANK"])
    # For simplicity, using CPU. In a multi-GPU setup, you'd assign a specific GPU.
    device = torch.device("cpu")

    model = nn.Linear(10, 2).to(device)
    # When world_size is 1, DDP wraps the model but doesn't perform actual distribution.
    model = DDP(model)

    optimizer = optim.SGD(model.parameters(), lr=0.01)
    criterion = nn.MSELoss()

    x = torch.randn(8, 10).to(device)
    y = torch.randn(8, 2).to(device)

    optimizer.zero_grad()

    output = model(x)

    loss = criterion(output, y)

    loss.backward()

    optimizer.step()

    print("Loss:", loss.item())

    # Destroy the process group at the end
    dist.destroy_process_group()

if __name__ == "__main__":
    main()

Loss: 2.249904155731201
